name: jsalt_gluon_nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - perl
  - sphinx=1.7.2
  - spacy
  - nltk
  - pytest
  - flaky
  - pytest-cov
  - jupyter
  - pip:
    - mxnet>=1.3.0b20180612
    - gluonnlp==0.3.0
    - https://github.com/mli/notedown/tarball/master
    - jupyter_contrib_nbextensions
